version: '3.8'

services:
  app:
    image: ${DOCKER_HUB_USERNAME}/ai_geologia:latest
    volumes:
      - /home/deployer/ai_geologia/relatorios:/app/relatorios
    networks:
      - ai_geologia_network
    labels:
      - traefik.enable=true
      - traefik.http.routers.geologia_app.rule=Host(`geologia.smartautohub.net`)
      - traefik.http.services.geologia_app.loadbalancer.server.port=6248
      - traefik.http.routers.geologia_app.service=geologia_app
      - traefik.http.routers.geologia_app.tls.certresolver=letsencryptresolver
      - traefik.http.routers.geologia_app.entrypoints=websecure
      - traefik.http.routers.geologia_app.tls=true

networks:
  ai_geologia_network:
    name: traefik_public
    external: true
